### PR TITLE
Added support for ODROID-C1 kernel

### PR DESCRIPTION
**Pull request by graugans**
For this an adaption of the original recipe had been needed. Most of the
odroid-u2 specifica had been suffixed with odroid-u2.

Signed-off-by: Christian Ege k4230r6@gmail.com

### CODE REVIEW

**Comment by stoupa-cz** [comment]
Hi,

perfect, thanks a lot! I have out of the office now, so I will test it tomorrow and merge it afterwards.

Tomas

**Comment by stoupa-cz** [comment]
I tried the resulting uImage and it is bootable. The build creates some QA error and misses a creation of dtb, but I will address this later.

**Comment by stoupa-cz** [comment]
And I forgot... thanks for you work!

**Comment by wetekenigma** [comment]
No worry, I ordered a odroid-c1 so I  can test stuff by myself.

**Pull request merged**
