### PR TITLE
Proposal for an odroid-c1 SD-Card image

### PR DESCRIPTION
**Pull request by graugans**
This is derived from the Raspberry PI SD-Card image. There is still some polishing needed. For example and initramfs and the boot.ini seems to be missing. This is intended to be a good starting point.

### CODE REVIEW

**Comment by stoupa-cz** [comment]
Yes, that was the part I also would like to make. I'm now busy with other stuff so I will work on it on Friday. In the meantime, I was trying to create DTB file in an OE way (following lines in the linux recipe):

   require recipes-kernel/linux/linux-dtb.inc
   KERNEL_DEVICETREE_odroid-c1 = "meson8b_odroidc.dtb"

But it failed. We should also add DTB to the resulting SD image.

By the way - is initramfs really needed? I know that Ubuntu provided by hardkernel has it.

**Comment by graugans** [comment]
Ye, I added this as a proposal for not doing stuff twice :). I am not sure if initramfs is needed. On another amlogic platform SD-Card booting was more reliable with initramfs. I already have everything in place for initramfs an d none initramfs so shouldn't be a big issue. 

I am busy as-well maybe I'll find some time at the weekend...

**Comment by stoupa-cz** [comment]
Yes, good start, I will definitely start on top of it.

Regarding initramfs - it isn't a big issue. And if it will somehow help for
stability, we will use it definitely.

**Comment by graugans** [comment]
Related to dtb, I just stumbled across [this](https://github.com/cottsay/linux/commit/8987c75563ed089c31041aaf6934823458b9e491?diff=unified)
A big thank you  to @cottsay for the finding

**Comment by graugans** [comment]
Updated PR to provide boot.ini + DTB

**Pull request merged**
